[daemon]
api_socket = "/tmp/syncd-demo-n2.sock"
log_level  = "debug"

[[pairs]]
id        = "demo"
mode      = "p2p"
local     = "~/sync-demo"
direction = "bidirectional"
interval  = 10

[pairs.provider]
port    = 5556
peers   = ["NODE_1:5556"]
node_id = "node_2"
